<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>SCANsat.Unity</RootNamespace>
    <AssemblyName>SCANsat.Unity</AssemblyName>
    <TargetFramework>net4.8</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
	  <KSPBT_GenerateAssemblyAttribute>false</KSPBT_GenerateAssemblyAttribute>
	  <KSPBT_GenerateDependencyAttributes>true</KSPBT_GenerateDependencyAttributes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.1.1" />
    <PackageReference Include="KSPCommunityLib" Version="0.1.1" />
  </ItemGroup>
</Project>