<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>SCANmechjeb</RootNamespace>
    <AssemblyName>SCANmechjeb</AssemblyName>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
	  <KSPBT_GenerateAssemblyAttribute>true</KSPBT_GenerateAssemblyAttribute>
	  <KSPBT_GenerateDependencyAttributes>true</KSPBT_GenerateDependencyAttributes>
  </PropertyGroup>
  <ItemGroup>
    <ModReference Include="MechJeb2">
      <DLLPath>GameData/MechJeb2/Plugins/MechJeb2.dll</DLLPath>
      <CKANIdentifier>MechJeb2</CKANIdentifier>
	  <KSPAssemblyVersion>2.5</KSPAssemblyVersion>
    </ModReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.1.1" />
    <PackageReference Include="KSPCommunityLib" Version="0.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SCANsat\SCANsat.csproj" />
  </ItemGroup>
</Project>
