<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>SCANsat</RootNamespace>
    <AssemblyName>SCANsat</AssemblyName>
    <TargetFramework>net4.8</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <KSPBT_GenerateAssemblyAttribute>true</KSPBT_GenerateAssemblyAttribute>
    <KSPBT_GenerateDependencyAttributes>true</KSPBT_GenerateDependencyAttributes>
  </PropertyGroup>
  <ItemGroup>
    <KSPVersionFile Include="$(KSPBT_ModRoot)/SCANsat.version">
      <Destination>$(KSPBT_ModRoot)/SCANsat.version</Destination>
      <KSP_Version>1.12.5</KSP_Version>
      <KSP_Version_Min>1.12.3</KSP_Version_Min>
      <KSP_Version_Max>1.12.5</KSP_Version_Max>
    </KSPVersionFile>
  </ItemGroup>
  <ItemGroup>
	<ModReference Include="KSPTextureLoader">
	  <DLLPath>GameData/KSPTextureLoader/Plugins/KSPTextureLoader.dll</DLLPath>
	  <CKANIdentifier>KSPTextureLoader</CKANIdentifier>
      <KSPAssemblyVersion>1.0.34</KSPAssemblyVersion>
	</ModReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.1.1" />
    <PackageReference Include="KSPCommunityLib" Version="0.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SCANsat.Unity/SCANsat.Unity.csproj" />
  </ItemGroup>
</Project>